### PR TITLE
Amulya-coder/Enhancement/Update UI

### PR DESCRIPTION
**Pull request by Amulya-coder**

### CODE REVIEW

**Comment by Amulya-coder** [comment]
@stephin007 Changes have been made .Please review it.

**Comment by Amulya-coder** [comment]
@stephin007 Now is it Right?

**Comment by Amulya-coder** [comment]
@stephin007 Changed the Branch name .Now Is it OK.

**Comment by stephin007** [comment]
The branch Name, is okay, but the chnges are not so much suitable and i had set that font which you changed was told to me by the client beacuse they liked it!
I cannot merge this PR 😞 sorry.

Great work though. I have other open sourced projects in my profile, you can contribute in that.

**Pull request closed without merging**
