### PR TITLE
Updated 404 page

### PR DESCRIPTION
**Pull request by sudeepshukla930**
Hey @stephin007 ,

I have **Updated 404 page**.
Hope you will like it.
Please review it.
If everything works fine. please merge it with **"hacktoberfest-accepted"** tag

### CODE REVIEW

**Comment by stephin007** [comment]
Will this run when the user routes to different page??
And also please raise this PR from a different branch! not from your master

**Comment by sudeepshukla930** [comment]
@stephin007 ,
Yes it will work.
I am doing it with new branch just give me five min

**Comment by sudeepshukla930** [comment]
@stephin007 , Sir I was trying but already the changes have been made through master branch that why it is not happening.
Can you please merge it through master

**Comment by stephin007** [comment]
Hi @sudeepshukla930 , sorry but I need to first check your changes in my local, then only I can merge it!

**Comment by sudeepshukla930** [comment]
Hey @stephin007 , no problem .
Can i send the code file through mail . So you can check into your local machine ?

**Comment by stephin007** [comment]
mail me please! @sudeepshukla930 
You can mail me from the mail i provided in my profile!

**Comment by sudeepshukla930** [comment]
Hey @stephin007 , 
I have mailed you.
please review it

**Comment by sudeepshukla930** [comment]
Hey @stephin007 ,
Is there is any issue in my pulll request??
Actually it has not been merged

**Comment by stephin007** [comment]
hey @sudeepshukla930 , sorry for replying late
This 404 page won't work, since the CSS used in this is not inline, firebase won't render this file!

**Pull request closed without merging**
